INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'1','1')
INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'1','1')
INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'1','1')
INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'1','1')

INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'1','2')
INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'1','2')
INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'1','2')
INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'1','2')

INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'2','2')
           
INSERT INTO [DGGV].[dbo].[Result]
           ([resultDuration]
           ,[resultOpinion]
           ,[resultType]
           ,[status]
           ,[criterionID]
           ,[studentID]
           ,[subjectID],[teacherID])VALUES('1'  ,null ,'1' ,'submit' ,'1','1' ,'2','1')
