INSERT INTO [DGGV].[dbo].[Student_Subject] ([studentID],[subjectID]) VALUES ('1','1')
INSERT INTO [DGGV].[dbo].[Student_Subject] ([studentID],[subjectID]) VALUES ('1','2')
INSERT INTO [DGGV].[dbo].[Student_Subject] ([studentID],[subjectID]) VALUES ('1','3')
INSERT INTO [DGGV].[dbo].[Student_Subject] ([studentID],[subjectID]) VALUES ('1','4')
INSERT INTO [DGGV].[dbo].[Student_Subject] ([studentID],[subjectID]) VALUES ('2','1')
INSERT INTO [DGGV].[dbo].[Student_Subject] ([studentID],[subjectID]) VALUES ('2','2')
INSERT INTO [DGGV].[dbo].[Student_Subject] ([studentID],[subjectID]) VALUES ('2','3')
INSERT INTO [DGGV].[dbo].[Student_Subject] ([studentID],[subjectID]) VALUES ('2','4')